import type { Category, Product } from '@/types/product.types';
import type { User } from '@/types/user.types';
import type { Order } from '@/types/order.types';

export const MOCK_CATEGORIES: Category[] = [
  { id: 'cat-1', name: 'Groceries', icon: '🛒', color: '#30F2C2' },
  { id: 'cat-2', name: 'Dairy', icon: '🥛', color: '#6BE8FF' },
  { id: 'cat-3', name: 'Fruits & Veg', icon: '🥦', color: '#2ED573' },
  { id: 'cat-4', name: 'Medicines', icon: '💊', color: '#FF5D73' },
  { id: 'cat-5', name: 'Snacks', icon: '🍿', color: '#FFB84D' },
  { id: 'cat-6', name: 'Household', icon: '🧹', color: '#7A5AF8' },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    name: 'Tata Sampann Toor Dal',
    description: 'Premium quality toor dal, carefully sorted and cleaned. Rich in protein and perfect for everyday cooking.',
    image: '🫘',
    price: 135,
    mrp: 165,
    discount: 18,
    unit: '1 kg',
    category: 'cat-1',
    shopId: 'shop-1',
    inStock: true,
    rating: 4.5,
    reviewCount: 234,
  },
  {
    id: 'prod-2',
    name: 'Amul Gold Milk',
    description: 'Full cream pasteurized milk with rich taste. Great for tea, coffee, and cooking.',
    image: '🥛',
    price: 34,
    mrp: 36,
    discount: 6,
    unit: '500 ml',
    category: 'cat-2',
    shopId: 'shop-1',
    inStock: true,
    rating: 4.7,
    reviewCount: 892,
  },
  {
    id: 'prod-3',
    name: 'Fresh Banana (Robusta)',
    description: 'Farm-fresh robusta bananas. Sweet, nutritious and great for breakfast or snacking.',
    image: '🍌',
    price: 45,
    mrp: 55,
    discount: 18,
    unit: '1 dozen',
    category: 'cat-3',
    shopId: 'shop-2',
    inStock: true,
    rating: 4.3,
    reviewCount: 156,
  },
  {
    id: 'prod-4',
    name: 'Crocin Advance',
    description: 'Fast relief from headache, body ache, and fever. Effective pain relief tablet.',
    image: '💊',
    price: 30,
    mrp: 32,
    discount: 6,
    unit: '10 tablets',
    category: 'cat-4',
    shopId: 'shop-3',
    inStock: true,
    rating: 4.6,
    reviewCount: 445,
  },
  {
    id: 'prod-5',
    name: 'Lay\'s Classic Salted',
    description: 'Crispy and crunchy potato chips with the perfect amount of salt.',
    image: '🥔',
    price: 20,
    mrp: 20,
    discount: 0,
    unit: '52 g',
    category: 'cat-5',
    shopId: 'shop-1',
    inStock: true,
    rating: 4.4,
    reviewCount: 678,
  },
  {
    id: 'prod-6',
    name: 'Vim Dishwash Liquid',
    description: 'Powerful dishwashing liquid with lemon freshness. Cuts through tough grease easily.',
    image: '🧴',
    price: 99,
    mrp: 125,
    discount: 21,
    unit: '500 ml',
    category: 'cat-6',
    shopId: 'shop-2',
    inStock: true,
    rating: 4.2,
    reviewCount: 321,
  },
  {
    id: 'prod-7',
    name: 'Aashirvaad Atta',
    description: 'India\'s most trusted whole wheat flour for soft rotis every time.',
    image: '🌾',
    price: 270,
    mrp: 320,
    discount: 16,
    unit: '5 kg',
    category: 'cat-1',
    shopId: 'shop-1',
    inStock: true,
    rating: 4.6,
    reviewCount: 1205,
  },
  {
    id: 'prod-8',
    name: 'Mother Dairy Paneer',
    description: 'Fresh and soft paneer made from pure cow milk. Perfect for curries and snacks.',
    image: '🧀',
    price: 90,
    mrp: 105,
    discount: 14,
    unit: '200 g',
    category: 'cat-2',
    shopId: 'shop-1',
    inStock: true,
    rating: 4.4,
    reviewCount: 389,
  },
  {
    id: 'prod-9',
    name: 'Shimla Apple (Royal)',
    description: 'Handpicked royal apples from Shimla. Crisp, juicy, and full of natural sweetness.',
    image: '🍎',
    price: 180,
    mrp: 220,
    discount: 18,
    unit: '1 kg',
    category: 'cat-3',
    shopId: 'shop-2',
    inStock: true,
    rating: 4.5,
    reviewCount: 267,
  },
  {
    id: 'prod-10',
    name: 'Dettol Antiseptic Liquid',
    description: 'Trusted antiseptic for first aid, personal hygiene, and household cleaning.',
    image: '🧪',
    price: 210,
    mrp: 250,
    discount: 16,
    unit: '500 ml',
    category: 'cat-4',
    shopId: 'shop-3',
    inStock: false,
    rating: 4.7,
    reviewCount: 534,
  },
  {
    id: 'prod-11',
    name: 'Haldiram\'s Aloo Bhujia',
    description: 'Crispy and spicy potato noodle snack. A perfect tea-time companion.',
    image: '🍜',
    price: 55,
    mrp: 65,
    discount: 15,
    unit: '200 g',
    category: 'cat-5',
    shopId: 'shop-1',
    inStock: true,
    rating: 4.5,
    reviewCount: 712,
  },
  {
    id: 'prod-12',
    name: 'Harpic Power Plus',
    description: 'Kills 99.9% germs. 10x better cleaning for your toilet bowl.',
    image: '🚽',
    price: 85,
    mrp: 99,
    discount: 14,
    unit: '500 ml',
    category: 'cat-6',
    shopId: 'shop-2',
    inStock: true,
    rating: 4.3,
    reviewCount: 198,
  },
];

export const MOCK_BANNERS = [
  {
    id: 'banner-1',
    title: 'Flat 30% Off',
    subtitle: 'On all grocery items this weekend!',
    cta: 'Shop Now',
    bgFrom: '#30F2C2',
    bgTo: '#6BE8FF',
  },
  {
    id: 'banner-2',
    title: 'Free Delivery',
    subtitle: 'On orders above ₹299 — no code needed',
    cta: 'Order Now',
    bgFrom: '#7A5AF8',
    bgTo: '#FF5D73',
  },
  {
    id: 'banner-3',
    title: 'Fresh Fruits Sale',
    subtitle: 'Farm-fresh fruits at wholesale prices',
    cta: 'Explore',
    bgFrom: '#2ED573',
    bgTo: '#FFB84D',
  },
];

export const MOCK_SHOPS = [
  {
    id: 'shop-1',
    name: 'QuickMart',
    category: 'Grocery & Essentials',
    distance: '0.5 km',
    rating: 4.5,
  },
  {
    id: 'shop-2',
    name: 'FreshBasket',
    category: 'Fruits & Vegetables',
    distance: '0.8 km',
    rating: 4.3,
  },
  {
    id: 'shop-3',
    name: 'MedPlus Pharmacy',
    category: 'Medicines & Wellness',
    distance: '1.2 km',
    rating: 4.6,
  },
];

export const MOCK_USER: User = {
  id: 'user-1',
  name: 'Arvind Kumar',
  phone: '9876543210',
  email: 'arvind@example.com',
  addresses: [
    {
      id: 'addr-1',
      label: 'Home',
      line1: '42, Whitefield Main Road, Bangalore',
      city: 'Bangalore',
      pincode: '560066',
      latitude: 12.9716,
      longitude: 77.5946,
    },
    {
      id: 'addr-2',
      label: 'Work',
      line1: '5th Floor, Prestige Tech Park',
      city: 'Bangalore',
      pincode: '560103',
      latitude: 12.9352,
      longitude: 77.6245,
    },
  ],
};

export const MOCK_ORDERS: Order[] = [
  {
    id: 'ORD-2024-001',
    status: 'delivered',
    shopName: 'QuickMart',
    items: [
      { productId: 'prod-2', name: 'Amul Gold Milk', quantity: 2, price: 34 },
      { productId: 'prod-5', name: 'Lay\'s Classic Salted', quantity: 3, price: 20 },
      { productId: 'prod-1', name: 'Tata Sampann Toor Dal', quantity: 1, price: 135 },
    ],
    totalAmount: 263,
    deliveryAddress: '42, Whitefield Main Road, Bangalore',
    createdAt: '2024-08-20T10:30:00Z',
    estimatedDelivery: '2024-08-20T11:00:00Z',
  },
  {
    id: 'ORD-2024-002',
    status: 'out_for_delivery',
    shopName: 'FreshBasket',
    items: [
      { productId: 'prod-3', name: 'Fresh Banana (Robusta)', quantity: 1, price: 45 },
      { productId: 'prod-9', name: 'Shimla Apple (Royal)', quantity: 2, price: 180 },
    ],
    totalAmount: 405,
    deliveryAddress: '42, Whitefield Main Road, Bangalore',
    createdAt: '2024-08-22T14:15:00Z',
    estimatedDelivery: '2024-08-22T14:45:00Z',
    deliveryPartner: {
      name: 'Raju Sharma',
      phone: '9988776655',
    },
  },
  {
    id: 'ORD-2024-003',
    status: 'placed',
    shopName: 'MedPlus Pharmacy',
    items: [
      { productId: 'prod-4', name: 'Crocin Advance', quantity: 1, price: 30 },
    ],
    totalAmount: 60,
    deliveryAddress: '5th Floor, Prestige Tech Park',
    createdAt: '2024-08-23T08:00:00Z',
    estimatedDelivery: '2024-08-23T08:30:00Z',
  },
];

export const POPULAR_SEARCHES = [
  'Milk', 'Bread', 'Rice', 'Eggs', 'Sugar', 'Oil', 'Atta', 'Dal',
];
