import { useEffect, useRef, useState } from 'react';
import { StyleSheet, View, Pressable } from 'react-native';

import { ThemedText } from '@/components/themed-text';
import { Button } from '@/components/ui/button';
import { OtpInput } from '@/components/ui/otp-input';
import { Screen } from '@/components/ui/screen';
import { Radius, Spacing } from '@/constants/theme';
import { useTheme } from '@/hooks/use-theme';
import * as partnerApi from '@/services/mock-partner-api';
import { useDelivery } from '@/state/delivery-context';

/**
 * Delivery / drop-off OTP flow (Master PRD §10.4.3 "Delivery" state, TASKS.md
 * item 8, the final screen of the Phase 0 core delivery loop). Reached via
 * `router.push('/delivery-otp')` from the in-transit screen's "Reached
 * Location" handler, same in-stack-push pattern the sixth session used for
 * pickup → in-transit — see HANDOFF.md "Important decisions" (seventh
 * session) for why this stays a push rather than a fourth top-level state
 * gate, same reasoning as before: `(delivery)` is already mounted for the
 * whole loop.
 *
 * Three local states, kept in one screen rather than split into routes —
 * same reasoning `verification-pending.tsx` and the pickup screen both used
 * for their own local sub-phases (these aren't independently deep-linkable
 * steps):
 *  - entering the 6-digit delivery OTP (mock rule below)
 *  - the PRD §10.9 "3 wrong attempts → 1-minute lock → last-4-of-customer-
 *    phone fallback" edge case
 *  - the terminal "Delivered ✓" confirmation before returning to `(tabs)`
 *
 * Mock rule (new this session, since there's no real OTP backend to compare
 * against): any 6-digit code succeeds *except* the literal code `000000`,
 * reserved specifically so the §10.9 lockout path can actually be exercised
 * in this mock — same spirit as "any 6-digit OTP is accepted" elsewhere in
 * the app, just with one reserved "wrong code" value carved out so this
 * screen's own most important edge case isn't otherwise unreachable. The
 * last-4-of-customer-phone fallback is a real check, not a mock shortcut —
 * it's compared against `activeDelivery.customerPhoneLast4`, generated by
 * `mock-partner-api.ts` alongside the rest of the mock request.
 */

const OTP_LENGTH = 6;
const FALLBACK_LENGTH = 4;
const MAX_ATTEMPTS = 3;
const LOCKOUT_MS = 60_000;
const DELIVERED_DISPLAY_MS = 1800;
/** Reserved "always wrong" code — see doc comment above. */
const RESERVED_WRONG_CODE = '000000';

export default function DeliveryOtpScreen() {
  const theme = useTheme();
  const { activeDelivery, completeDelivery } = useDelivery();

  const [mode, setMode] = useState<'otp' | 'fallback'>('otp');
  const [otp, setOtp] = useState('');
  const [fallbackCode, setFallbackCode] = useState('');
  const [attempts, setAttempts] = useState(0);
  const [lockedUntil, setLockedUntil] = useState<number | null>(null);
  const [secondsLeft, setSecondsLeft] = useState(0);
  const [error, setError] = useState<string | null>(null);
  const [fallbackError, setFallbackError] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [delivered, setDelivered] = useState(false);
  const [photoStatus, setPhotoStatus] = useState<'pending' | 'capturing' | 'captured'>('pending');

  const deliveredTimeoutRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  const isLocked = lockedUntil !== null && secondsLeft > 0;

  // Countdown tick while locked; auto-unlocks and resets attempts once the
  // minute is up, per PRD §10.9 ("locks the OTP field for 1 minute").
  useEffect(() => {
    if (lockedUntil === null) return;
    const tick = () => {
      const remaining = Math.max(0, Math.ceil((lockedUntil - Date.now()) / 1000));
      setSecondsLeft(remaining);
      if (remaining <= 0) {
        setLockedUntil(null);
        setAttempts(0);
        setError(null);
        setOtp('');
      }
    };
    tick();
    const interval = setInterval(tick, 1000);
    return () => clearInterval(interval);
  }, [lockedUntil]);

  useEffect(() => {
    return () => {
      if (deliveredTimeoutRef.current) clearTimeout(deliveredTimeoutRef.current);
    };
  }, []);

  // Defensive only — this screen is only ever pushed to from the in-transit
  // screen's "Reached Location" handler, which only runs while a delivery is
  // active, but the type is nullable.
  if (!activeDelivery) return null;

  // TS's narrowing from the guard above doesn't propagate into
  // `handleSubmitFallback`, a separately-declared function below that reads
  // `activeDelivery.customerPhoneLast4` — a real `tsc` run (finally
  // possible this session, see HANDOFF.md) caught this as a genuine
  // TS18047 error, not a false positive. Capturing the narrowed value into
  // its own `const` here fixes it: unlike `activeDelivery` itself (a hook
  // return value), a local `const` never reassigned keeps the non-null type
  // TS inferred at its declaration, even inside a closure declared later in
  // the same scope.
  const delivery = activeDelivery;

  function markDelivered() {
    setDelivered(true);
    deliveredTimeoutRef.current = setTimeout(completeDelivery, DELIVERED_DISPLAY_MS);
  }

  function handleSimulatePhoto() {
    setPhotoStatus('capturing');
    setTimeout(() => {
      setPhotoStatus('captured');
    }, 1500);
  }

  async function handleSubmitOtp() {
    if (otp.length !== OTP_LENGTH || isLocked || loading) return;
    setError(null);
    setLoading(true);
    try {
      if (otp === RESERVED_WRONG_CODE) {
        const nextAttempts = attempts + 1;
        setAttempts(nextAttempts);
        setOtp('');
        if (nextAttempts >= MAX_ATTEMPTS) {
          setLockedUntil(Date.now() + LOCKOUT_MS);
        } else {
          setError(`Incorrect code. ${MAX_ATTEMPTS - nextAttempts} attempt(s) left.`);
        }
        return;
      }
      await partnerApi.confirmDelivery();
      markDelivered();
    } finally {
      setLoading(false);
    }
  }

  async function handleSubmitFallback() {
    if (fallbackCode.length !== FALLBACK_LENGTH || loading) return;
    setFallbackError(null);
    setLoading(true);
    try {
      if (fallbackCode !== delivery.customerPhoneLast4) {
        setFallbackError("That doesn't match our records. Try again.");
        setFallbackCode('');
        return;
      }
      await partnerApi.confirmDelivery();
      markDelivered();
    } finally {
      setLoading(false);
    }
  }

  if (delivered) {
    return (
      <Screen scroll>
        <View style={styles.deliveredWrap}>
          <ThemedText type="h1" style={styles.deliveredCheck}>
            ✅
          </ThemedText>
          <ThemedText type="h2">Delivered!</ThemedText>
          <ThemedText type="body" themeColor="textSecondary" style={styles.centerText}>
            Nice work — order {activeDelivery.id} is marked complete.
          </ThemedText>
          <View style={styles.deliveredFooter}>
            <Button label="Done" onPress={completeDelivery} />
          </View>
        </View>
      </Screen>
    );
  }

  return (
    <Screen scroll>
      <View style={styles.header}>
        <ThemedText type="caption" themeColor="textSecondary">
          DELIVERY
        </ThemedText>
        <ThemedText type="h2">Confirm the code with the customer</ThemedText>
        <ThemedText type="small" themeColor="textSecondary">
          {activeDelivery.itemsSummary} · Order ID: {activeDelivery.id}
        </ThemedText>
      </View>

      <ThemedText type="bodyBold" style={styles.photoLabel}>
        Photo of delivered items
      </ThemedText>
      <ThemedText type="small" themeColor="textSecondary" style={styles.photoHint}>
        Required before you can complete the delivery.
      </ThemedText>

      {photoStatus !== 'captured' ? (
        <Pressable
          onPress={handleSimulatePhoto}
          disabled={photoStatus === 'capturing'}
          accessibilityRole="button"
          style={[
            styles.photoTile,
            { borderColor: theme.border, backgroundColor: theme.surface, opacity: photoStatus === 'capturing' ? 0.6 : 1 },
          ]}>
          <ThemedText type="h1">📷</ThemedText>
          <ThemedText type="small" themeColor="textSecondary" style={styles.centerText}>
            {photoStatus === 'capturing'
              ? 'Capturing…'
              : 'Tap to simulate photo capture'}
          </ThemedText>
        </Pressable>
      ) : (
        <View style={[styles.photoTile, { borderColor: theme.success, backgroundColor: theme.surface }]}>
          <ThemedText type="h1">✅</ThemedText>
          <ThemedText type="small" themeColor="textSecondary" style={styles.centerText}>
            Photo captured
          </ThemedText>
        </View>
      )}

      {mode === 'otp' ? (
        <View style={styles.form}>
          <ThemedText type="bodyBold">Ask the customer for their 6-digit delivery code</ThemedText>
          <OtpInput length={OTP_LENGTH} value={otp} onChange={setOtp} error={!!error} />
          {error ? (
            <ThemedText type="small" themeColor="error">
              {error}
            </ThemedText>
          ) : null}

          {isLocked ? (
            <View style={[styles.lockBanner, { backgroundColor: theme.backgroundElement, borderColor: theme.border }]}>
              <ThemedText type="smallBold" themeColor="warning">
                Locked — try again in 0:{secondsLeft.toString().padStart(2, '0')}
              </ThemedText>
              <ThemedText
                type="smallBold"
                themeColor="primary"
                onPress={() => setMode('fallback')}
                accessibilityRole="button"
                style={styles.fallbackLink}>
                Verify last 4 digits of the customer's phone instead
              </ThemedText>
            </View>
          ) : null}

          <View style={styles.footer}>
            <Button
              label="Mark Delivered"
              onPress={handleSubmitOtp}
              disabled={otp.length !== OTP_LENGTH || isLocked || photoStatus !== 'captured'}
              loading={loading}
            />
          </View>
        </View>
      ) : (
        <View style={styles.form}>
          <ThemedText type="bodyBold">Verify the customer's phone number</ThemedText>
          <ThemedText type="small" themeColor="textSecondary">
            Ask the customer for the last 4 digits of the phone number on their order.
          </ThemedText>
          <OtpInput length={FALLBACK_LENGTH} value={fallbackCode} onChange={setFallbackCode} error={!!fallbackError} />
          {fallbackError ? (
            <ThemedText type="small" themeColor="error">
              {fallbackError}
            </ThemedText>
          ) : null}

          <ThemedText
            type="smallBold"
            themeColor="primary"
            onPress={() => setMode('otp')}
            accessibilityRole="button"
            style={styles.fallbackLink}>
            Back to code entry
          </ThemedText>

          <View style={styles.footer}>
            <Button
              label="Mark Delivered"
              onPress={handleSubmitFallback}
              disabled={fallbackCode.length !== FALLBACK_LENGTH || photoStatus !== 'captured'}
              loading={loading}
            />
          </View>
        </View>
      )}
    </Screen>
  );
}

const styles = StyleSheet.create({
  header: { gap: Spacing.half, marginBottom: Spacing.four },
  form: { gap: Spacing.two, marginTop: Spacing.four },
  centerText: { textAlign: 'center' },
  photoLabel: { marginBottom: Spacing.half },
  photoHint: { marginBottom: Spacing.three },
  photoTile: {
    borderRadius: Radius.lg,
    borderWidth: 1.5,
    borderStyle: 'dashed',
    paddingVertical: Spacing.five,
    paddingHorizontal: Spacing.four,
    alignItems: 'center',
    gap: Spacing.one,
  },
  lockBanner: {
    borderRadius: Radius.md,
    borderWidth: 1.5,
    padding: Spacing.three,
    gap: Spacing.one,
  },
  fallbackLink: { marginTop: Spacing.one },
  footer: { paddingBottom: Spacing.two, paddingTop: Spacing.four },
  deliveredWrap: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: Spacing.one, paddingTop: Spacing.six },
  deliveredCheck: { fontSize: 56, marginBottom: Spacing.two },
  deliveredFooter: { alignSelf: 'stretch', paddingTop: Spacing.five },
});
